# Generated by Django 3.0.5 on 2021-11-17 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=100, unique=True)),
                ('short_url', models.CharField(max_length=20, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
