# Generated by Django 3.0.5 on 2021-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
